name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  go_install:
    runs-on: ubuntu-latest
    steps:
      - uses: rlespinasse/github-slug-action@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ^1.21
      - run: cd /tmp && go install github.com/Antonboom/testifylint@${{ env.GITHUB_REF_NAME }} && testifylint -h

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.0
          args: --timeout=5m

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ^1.21
      - uses: actions/checkout@v3
      - run: go test -coverpkg=./analyzer,./internal/analysisutil,./internal/checkers,./internal/config -coverprofile=coverage.out ./...
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
